### ISSUE TITLE
Unexpected keyword error in mission generation script

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/Houston#163]
```
(houston-kIZ820NQ) chris@nostromo:~/houston/experiments$ ./generate_missions.py 1 10
Traceback (most recent call last):
  File "./generate_missions.py", line 52, in <module>
    args.seed, args.output_file)
  File "./generate_missions.py", line 39, in generate
    mission_generator = RandomMissionGenerator(sut, initial, environment, config, max_num_commands=max_num_commands) #action_generators=[CircleBasedGotoGenerator((-35.3632607, 149.1652351), 2.0)])
TypeError: __init__() got an unexpected keyword argument 'max_num_commands'
```

**Comment by ChrisTimperley** [comment]
> Is it importing the right code? it works for me:
> 
> ```
> python experiments/generate_missions.py 1 10
> Generated mission: 1
> Done with generating missions
> ```
> 
> `max_num_commands` is an argument for `RandomMissionGenerator` unless when it's importing `houston` it is actually importing something really old

Ah. I pulled a bunch of updates onto Nostromo but forgot to run `pip install .` afterwards. Thanks!
